"""delete_test

Revision ID: 2ee9135142b2
Revises: e62205f38e6f
Create Date: 2024-08-26 23:18:50.083599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee9135142b2'
down_revision = 'e62205f38e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_reviews', schema=None) as batch_op:
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
