"""Average Steam Positive and Negative

Revision ID: 4ea308944d64
Revises: 524c17cfa7e2
Create Date: 2024-09-02 15:34:00.109978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea308944d64'
down_revision = '524c17cfa7e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steam_pos_avg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('steam_neg_avg', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_reviews', schema=None) as batch_op:
        batch_op.drop_column('steam_neg_avg')
        batch_op.drop_column('steam_pos_avg')

    # ### end Alembic commands ###
