"""unique_constraint_game_news_link

Revision ID: 5232d5d9937c
Revises: ab7bf7e43820
Create Date: 2024-09-07 15:01:38.391546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5232d5d9937c'
down_revision = 'ab7bf7e43820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_news', schema=None) as batch_op:
        batch_op.create_unique_constraint('_game_id_news_link_uc', ['game_id', 'link'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_news', schema=None) as batch_op:
        batch_op.drop_constraint('_game_id_news_link_uc', type_='unique')

    # ### end Alembic commands ###
