"""Review_Number_Scraped

Revision ID: 524c17cfa7e2
Revises: 
Create Date: 2024-08-29 21:53:22.145000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524c17cfa7e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_scraped', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_reviews', schema=None) as batch_op:
        batch_op.drop_column('number_scraped')

    # ### end Alembic commands ###
