"""thumbnail_link

Revision ID: ab7bf7e43820
Revises: 22f4a05b6d90
Create Date: 2024-09-07 14:35:20.541251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7bf7e43820'
down_revision = '22f4a05b6d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_news', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_link')

    # ### end Alembic commands ###
