"""Initial

Revision ID: e62205f38e6f
Revises: 
Create Date: 2024-08-26 23:17:23.108973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62205f38e6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_reviews', schema=None) as batch_op:
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###
